### ISSUE TITLE
对主线关卡扫荡的支持

### ISSUE THREAD

**Issue by 5upernova-heng** [TheFunny/ArisuAutoSweeper#10]
不知道 AAS 未来有没有添加扫荡主线关卡的打算？

不知道有没有我可以帮上忙的地方。可以发一些 Help Wanted Issue

**Comment by TheFunny** [comment]
对主线关卡的扫荡功能在计划中，但本人现在比较忙，等空闲了会安排上。

**Comment by 5upernova-heng** [comment]
> 对主线关卡的扫荡功能在计划中，但本人现在比较忙，等空闲了会安排上。

我可以帮忙写一个简单的，选定某一关然后扫荡的 task，如果你觉得没问题，我过几天就会提交 PR。
当然，如果你希望在扫荡主线上实现更复杂的功能，你也可以和我讨论一下，我或许能提上符合要求的 PR

如果你还是希望，这部分功能等你空闲下来自己写，我也表示理解。我主要是看到终于有基于 ALAS 框架的 BA 脚本了，能帮上一点忙，就想看看能不能帮帮忙。

**Comment by TheFunny** [comment]
我的想法是，参考咖啡厅选择学生的方式，用户输入想要扫荡的关卡与次数，脚本读取后进行操作。

需要使用的模块 `stage` 下的 `ap` `list` `sweep`，`ui` 下的 `ui_ensure_index` 函数。因为主线的识别区域不同，在创建 `SweepList` 相应实例时需要更改相应的识别图片。`list` 目前只接受数字的 index，故主线关卡 ocr 的 `-` 需要处理一下，有些关卡有 `A` 的也需要处理一下。可以的话，请把主线扫荡相关的文件放在 `tasks/mission` 下。

**Comment by RedDeadDepresso** [comment]
Hi, would it be possible to also integrate MCE-Manager into AAS or would it be a bad idea? MCE-Manager is just the GUI Mission/Commissions/Event section of my Blue Archive script BAAuto.

Here is where I explain in detail how it works 
https://github.com/MaaAssistantArknights/MBA/issues/10 

and here is the source code for the task
https://github.com/RedDeadDepresso/BAAuto/blob/main/modules/mission.py.

My plan was that when opening AAS it would also open MCE-Manager and when running Mission/Commissions/Event it would read the configuration in MCE/config.json. I will probably have to update the GUI in MCE-Manager by adding a refresh button in the queue so that it sync after running AAS. You don't have to implement it if you think it's impractical, but it would be nice to have.

**Comment by 5upernova-heng** [comment]
看了一下 `/bounty` 和 `/sweep` 的代码，感觉我可能 Python 有些生疏了，让我来写主线扫荡，我可能写不太好。还是等你闲下来写吧，我再多学习一下你的代码。
