### ISSUE TITLE
添加支持国服

### ISSUE THREAD

**Issue by JenyuShiu** [TheFunny/ArisuAutoSweeper#23]
希望能够添加对国服的支持。

**Comment by RedDeadDepresso** [comment]
The national server shouldn't be difficult to implement, but the problem is the assets which are around 200. It would require someone to spend a lot of time taking screenshots with the emulator and cropping them in Adobe Photoshop.

I would simply recommend using this other Blue Archive Script, which supports the national server.
https://github.com/pur1fying/blue_archive_auto_script

If you feel brave in adapting AAS for the national server, you can fork the repository, work on the dev branch, create a folder called "zhs" and follow this guide to add the assets:
 https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/2.2.-Multi-server-support

**Comment by JenyuShiu** [comment]
Thanks for the answer. I'm actually using other scripts, but I prefer to use ArisuAutoSweeper.
I just want to know if support for the Chinese server version of Blue Archive is in your plans.
I'm not in a hurry, but very much looking forward to it being available on the Chinese server version of Blue Archive.

**Comment by RedDeadDepresso** [comment]
It would be impossible for me to implement the national server because it seems to require a Chinese phone number to create an account so it all depends on @TheFunny but they are very busy.

**Comment by JenyuShiu** [comment]
I see, thanks for taking the time to answer for me.
